### ISSUE TITLE
Provide meta prerequisites for automatic document generation

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/eslint-plugin-cypress#184]
This is a suggestion to provide or modify the necessary `meta` tags to enable automatic documentation generation using [eslint-doc-generator](https://github.com/bmish/eslint-doc-generator).

## ESLint doc generator recommendations

The ESLint organization recommends using the npm module [eslint-doc-generator](https://github.com/bmish/eslint-doc-generator) (Automatic documentation generator for ESLint plugins and rules) to support the generation of consistent documentation for ESLint plugins.

In its [Configure Linting](https://github.com/bmish/eslint-doc-generator/blob/main/README.md#configure-linting) documentation it recommends the following:

> ... enable the `recommended` rules from [eslint-plugin-eslint-plugin](https://github.com/eslint-community/eslint-plugin-eslint-plugin) as well as:

- [eslint-plugin/require-meta-docs-description](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/main/docs/rules/require-meta-docs-description.md) to ensure your rules have consistent descriptions for use in the generated docs
- [eslint-plugin/require-meta-docs-url](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/main/docs/rules/require-meta-docs-url.md) to ensure your rule docs are linked to by editors on highlighted violations
- [eslint-plugin/require-meta-schema](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/main/docs/rules/require-meta-schema.md) to ensure your rules have schemas for use in determining options

## Current compatibility

The repo is currently not compatible with the recommendations. The items in the following list can be checked off as they are addressed

Pass rules from:

- [x] [eslint-plugin/recommended](https://github.com/eslint-community/eslint-plugin-eslint-plugin)
- [x] [eslint-plugin/require-meta-docs-description](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/main/docs/rules/require-meta-docs-description.md)
- [x] [eslint-plugin/require-meta-docs-url](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/main/docs/rules/require-meta-docs-url.md)
- [x] [eslint-plugin/require-meta-schema](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/main/docs/rules/require-meta-schema.md)

The [eslint-plugin/recommended](https://github.com/eslint-community/eslint-plugin-eslint-plugin) rules fail due to `meta.type` and `meta.schema`. The rules [eslint-plugin/require-meta-docs-description](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/main/docs/rules/require-meta-docs-description.md) and [eslint-plugin/require-meta-docs-url](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/main/docs/rules/) fail individually.
